// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-boilerplate-api/bootstrap"
	"go-boilerplate-api/internal/app/api/grpc"
	"go-boilerplate-api/internal/app/api/http"
	"go-boilerplate-api/internal/app/api/http/handlers"
	"go-boilerplate-api/internal/app/repository"
	"go-boilerplate-api/internal/app/todo"
	"go-boilerplate-api/internal/pkg/db"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp() (*bootstrap.App, error) {
	gormDB := db.NewRDBMS()
	gormTodoRepository := repository.NewTodoRepository(gormDB)
	todoService := todo.NewTodoService(gormTodoRepository)
	todoController := handlers.NewTodoController(todoService)
	engine := http.NewApiRouter(todoController)
	server := bootstrap.NewHttpServer(engine)
	grpcTodoHandler := grpc.NewGRPCTodoHandler(todoService)
	grpcServer := grpc.NewGrpcServer(grpcTodoHandler)
	listener, err := bootstrap.NewGrpcListener()
	if err != nil {
		return nil, err
	}
	app := bootstrap.NewApiApp(server, grpcServer, listener)
	return app, nil
}
