// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/todo/v1/todo_service.proto

package todov1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_todo_v1_todo_service_proto protoreflect.FileDescriptor

const file_proto_todo_v1_todo_service_proto_rawDesc = "" +
	"\n" +
	" proto/todo/v1/todo_service.proto\x12\atodo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/todo/v1/todo.proto2\xd3\x03\n" +
	"\vTodoService\x12T\n" +
	"\n" +
	"CreateTodo\x12\x1a.todo.v1.CreateTodoRequest\x1a\x15.todo.v1.TodoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/todo\x12T\n" +
	"\tListTodos\x12\x19.todo.v1.ListTodosRequest\x1a\x1a.todo.v1.ListTodosResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/todo\x12U\n" +
	"\aGetTodo\x12\x17.todo.v1.GetTodoRequest\x1a\x15.todo.v1.TodoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/todo/{item_id}\x12^\n" +
	"\n" +
	"UpdateTodo\x12\x1a.todo.v1.UpdateTodoRequest\x1a\x15.todo.v1.TodoResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*2\x12/v1/todo/{item_id}\x12a\n" +
	"\n" +
	"DeleteTodo\x12\x1a.todo.v1.DeleteTodoRequest\x1a\x1b.todo.v1.DeleteTodoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/todo/{item_id}B\x89\x01\n" +
	"\vcom.todo.v1B\x10TodoServiceProtoP\x01Z+go-boilerplate-api/pkg/proto/todo/v1;todov1\xa2\x02\x03TXX\xaa\x02\aTodo.V1\xca\x02\aTodo\\V1\xe2\x02\x13Todo\\V1\\GPBMetadata\xea\x02\bTodo::V1b\x06proto3"

var file_proto_todo_v1_todo_service_proto_goTypes = []any{
	(*CreateTodoRequest)(nil),  // 0: todo.v1.CreateTodoRequest
	(*ListTodosRequest)(nil),   // 1: todo.v1.ListTodosRequest
	(*GetTodoRequest)(nil),     // 2: todo.v1.GetTodoRequest
	(*UpdateTodoRequest)(nil),  // 3: todo.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil),  // 4: todo.v1.DeleteTodoRequest
	(*TodoResponse)(nil),       // 5: todo.v1.TodoResponse
	(*ListTodosResponse)(nil),  // 6: todo.v1.ListTodosResponse
	(*DeleteTodoResponse)(nil), // 7: todo.v1.DeleteTodoResponse
}
var file_proto_todo_v1_todo_service_proto_depIdxs = []int32{
	0, // 0: todo.v1.TodoService.CreateTodo:input_type -> todo.v1.CreateTodoRequest
	1, // 1: todo.v1.TodoService.ListTodos:input_type -> todo.v1.ListTodosRequest
	2, // 2: todo.v1.TodoService.GetTodo:input_type -> todo.v1.GetTodoRequest
	3, // 3: todo.v1.TodoService.UpdateTodo:input_type -> todo.v1.UpdateTodoRequest
	4, // 4: todo.v1.TodoService.DeleteTodo:input_type -> todo.v1.DeleteTodoRequest
	5, // 5: todo.v1.TodoService.CreateTodo:output_type -> todo.v1.TodoResponse
	6, // 6: todo.v1.TodoService.ListTodos:output_type -> todo.v1.ListTodosResponse
	5, // 7: todo.v1.TodoService.GetTodo:output_type -> todo.v1.TodoResponse
	5, // 8: todo.v1.TodoService.UpdateTodo:output_type -> todo.v1.TodoResponse
	7, // 9: todo.v1.TodoService.DeleteTodo:output_type -> todo.v1.DeleteTodoResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_todo_v1_todo_service_proto_init() }
func file_proto_todo_v1_todo_service_proto_init() {
	if File_proto_todo_v1_todo_service_proto != nil {
		return
	}
	file_proto_todo_v1_todo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo_v1_todo_service_proto_rawDesc), len(file_proto_todo_v1_todo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todo_v1_todo_service_proto_goTypes,
		DependencyIndexes: file_proto_todo_v1_todo_service_proto_depIdxs,
	}.Build()
	File_proto_todo_v1_todo_service_proto = out.File
	file_proto_todo_v1_todo_service_proto_goTypes = nil
	file_proto_todo_v1_todo_service_proto_depIdxs = nil
}
